#!/bin/bash

# USB device 
deviceid="3151:1002"

# Automatically runs on wake/post after suspend
if [ "$1" = "post" ] && [ "$2" = "suspend" ]; then
    logger "USB Reset: usbreset sent to $deviceid"
    usbreset $deviceid
fi
